export const SetUpStyles = {
  addItemButton: {
    bgColor: 'bg-blue-600',
    hoverBgColor: 'hover:bg-blue-700',
  },
  headerBanner: {
    padding: 'p-4',
    bgColor: 'bg-blue-200',
    flex: 'flex',
    flexJustify: 'justify-between',
    rounded: 'rounded',
    shadow: 'shadow-lg',
  },
  headerWrapper: {
    bgColor: 'bg-white',
    height: 'h-16',
    padding: 'pb-1',
    position: 'sticky',
    top: 'top-0',
    width: 'w-1/2',
    zIndex: 'z-50',
  },
  input: {
    border: 'border-2 ',
    borderColor: 'border-gray-400',
    borderType: 'border-solid',
    rounded: 'rounded',
    textAlign: 'text-right',
  },
  line: {
    bgColor: 'odd:bg-gray-200 even:bg-white',
    flex: 'flex',
    flexJustify: 'justify-between',
    margin: 'mb-1',
    padding: 'p-2',
    rounded: 'rounded',
    shadow: 'shadow-md',
  },
  form: {
    bgColor: 'bg-white',
    zIndex: 'z-10',
  },
  section: {
    border: 'border-b-2',
    borderColor: 'border-gray-700',
    borderType: 'border-solid',
    margin: 'mb-4',
    padding: 'pb-2',
    width: 'w-1/2',
  },
  sectionTitle: {
    bgColor: 'bg-white',
    border: 'border-b-2',
    borderColor: 'border-gray-700',
    borderType: 'border-solid',
    fontSize: 'text-lg',
    margin: 'mb-2',
    padding: 'pl-2',
    position: 'sticky',
    textDecoration: 'underline',
    width: 'w-100',
    zIndex: 'z-30',
  },
  submitButton: {
    bgColor: 'bg-green-600',
    hoverBgColor: 'hover:bg-green-700',
  },
}
